### PR TITLE
Cubit 2020.2 compatibility fixes

### PR DESCRIPTION
**Pull request by bam241**
this allow me to compile the plugin vs `Cubit 2020.2`

Was able to compile it but did not tested it in `Cubit`.

### CODE REVIEW

**Comment by gonuke** [comment]
Did you mean to commit the long cmake file?

**Comment by bam241** [comment]
This is some left over of the macOS build forgot to clean that up.

**Comment by bam241** [comment]
removing all the ABI flags I was able to have the plugin loaded without segfault
but when running the test I got:
```
cubit.cmd('export dagmc "test.h5m" faceting_tolerance 1e-3 make_watertight verbose')

MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: no geometry sets exist in the model. Please check curve faceting.!
MOAB ERROR: make_mesh_watertight() line 1871 in MakeWatertight.cpp
Setting faceting tolerance to 0.001
Setting length tolerance to 0
Setting normal tolerance to 5
Found 0 entities of dimension 0
Found 0 entities of dimension 1
Found 0 entities of dimension 2
Found 0 entities of dimension 3
Could not make the model watertight.16
[2021-01-08 09:25:21.306] [error] Command Failed.

ERROR: test.jou (5). Command Failed.
%>

[2021-01-08 09:25:21.321] [error] Errors found during session.

ERROR: Errors found during session.
```

Any insights @ljacobson64 ?

**Comment by bam241** [comment]
reopening from Svalinn so action get access to secret...

**Pull request closed without merging**
