### PR TITLE
Updating for PyNE Submodule in DAGMC

### PR DESCRIPTION
**Pull request by gonuke**
Pushing this change in ahead of #86 for more immediate effect

### CODE REVIEW

**Comment by gonuke** [comment]
Do you know what's wrong here, @bam241 ?

**Comment by pshriwise** [comment]
I'm guessing there are a good number of installation scripts out there that will run into this same trouble. I'm thinking it would be good to have DAGMC initialize the PyNE repo as part of the CMake step. I'd be happy to put in that PR (into DAGMC).

**Comment by bam241** [comment]
there is 2 issues there:
- the secret are not accessible for PR issued from a fork.
- it is now pulling the new DAGMC with amalgamated PyNE.

the first one, when I designed the GitHub action I pictured it as run on merge, so secret would be accessible not an PR...
for the second one a fix is included in #86 

bottom line, I'd probably merge that one.

**Comment by gonuke** [comment]
Closing in favor of #91

**Pull request closed without merging**
